name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Install the local jar dependency (only needed if it's not in the remote repository)
    - name: Install local JAR dependency
      run: mvn install:install-file -Dfile=./src/main/resources/calculator-1.0.jar -DgroupId=com.epam.training -DartifactId=calculator -Dversion=1.0 -Dpackaging=jar

    # Run Maven clean, verify, and test phases in one step for efficiency
    - name: Run Maven build and tests
      run: mvn --batch-mode clean verify test -DskipTests=false -Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
